### ISSUE TITLE
Debug build fails

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#20] opened 2015-03-02 18:49 UTC
Arch Linux x86_64. Due to segmentation fault on scanning with Miam-Player my music folder (Library) I decided to build debug version, but it failed
```model/sqldatabase.cpp:512:9: warning: variable «oldArtistId» set but not used [-Wunused-but-set-variable]
    uint oldArtistId = 0;
         ^
model/sqldatabase.cpp: В функции-члене «void SqlDatabase::saveFileRef(const QString&)»:
model/sqldatabase.cpp:940:7: warning: variable «artistInserted» set but not used [-Wunused-but-set-variable]
  bool artistInserted = false;
       ^
In file included from /usr/include/qt/QtCore/qobject.h:43:0,
                 from /usr/include/qt/QtCore/QObject:1,
                 from model/genericdao.h:4,
                 from model/artistdao.h:4,
                 from model/sqldatabase.h:5,
                 from model/sqldatabase.cpp:1:
/usr/include/qt/QtCore/qlist.h: In instantiation of «void QList<T>::node_construct(QList<T>::Node*, const T&) [with T = PlaylistDAO]»:
/usr/include/qt/QtCore/qlist.h:521:32:   required from «void QList<T>::append(const T&) [with T = PlaylistDAO]»
model/sqldatabase.cpp:398:28:   required from here
/usr/include/qt/QtCore/qlist.h:378:35: error: use of deleted function «PlaylistDAO& PlaylistDAO::operator=(const PlaylistDAO&)»
     else *reinterpret_cast<T*>(n) = t;
                                   ^
In file included from model/sqldatabase.h:8:0,
                 from model/sqldatabase.cpp:1:
model/playlistdao.h:12:24: note: «PlaylistDAO& PlaylistDAO::operator=(const PlaylistDAO&)» is implicitly deleted because the default definition would be ill-formed:
 class MIAMCORE_LIBRARY PlaylistDAO : public GenericDAO
                        ^
model/playlistdao.h:12:24: error: use of deleted function «GenericDAO& GenericDAO::operator=(const GenericDAO&)»
In file included from model/artistdao.h:4:0,
                 from model/sqldatabase.h:5,
                 from model/sqldatabase.cpp:1:
model/genericdao.h:12:24: note: «GenericDAO& GenericDAO::operator=(const GenericDAO&)» is implicitly deleted because the default definition would be ill-formed:
 class MIAMCORE_LIBRARY GenericDAO : public QObject
                        ^
In file included from model/../miamcore_global.h:4:0,
                 from model/sqldatabase.h:4,
                 from model/sqldatabase.cpp:1:
/usr/include/qt/QtCore/qobject.h:463:5: error: «QObject& QObject::operator=(const QObject&)» is private
     Q_DISABLE_COPY(QObject)
     ^
In file included from model/artistdao.h:4:0,
                 from model/sqldatabase.h:5,
                 from model/sqldatabase.cpp:1:
model/genericdao.h:12:24: error: в данном контексте
 class MIAMCORE_LIBRARY GenericDAO : public QObject
                        ^
model/genericdao.h:12:24: error: use of deleted function «QObject& QObject::operator=(const QObject&)»
In file included from model/../miamcore_global.h:4:0,
                 from model/sqldatabase.h:4,
                 from model/sqldatabase.cpp:1:
/usr/include/qt/QtCore/qobject.h:463:5: note: declared here
     Q_DISABLE_COPY(QObject)
     ^
In file included from /usr/include/qt/QtCore/qobject.h:43:0,
                 from /usr/include/qt/QtCore/QObject:1,
                 from model/genericdao.h:4,
                 from model/artistdao.h:4,
                 from model/sqldatabase.h:5,
                 from model/sqldatabase.cpp:1:
/usr/include/qt/QtCore/qlist.h: In instantiation of «void QList<T>::node_construct(QList<T>::Node*, const T&) [with T = TrackDAO]»:
/usr/include/qt/QtCore/qlist.h:521:32:   required from «void QList<T>::append(const T&) [with T = TrackDAO]»
/usr/include/qt/QtCore/qlist.h:306:49:   required from «void QList<T>::push_back(const T&) [with T = TrackDAO]»
model/sqldatabase.cpp:354:37:   required from here
/usr/include/qt/QtCore/qlist.h:378:35: error: use of deleted function «TrackDAO& TrackDAO::operator=(const TrackDAO&)»
     else *reinterpret_cast<T*>(n) = t;
                                   ^
In file included from model/sqldatabase.h:7:0,
                 from model/sqldatabase.cpp:1:
model/trackdao.h:12:24: note: «TrackDAO& TrackDAO::operator=(const TrackDAO&)» is implicitly deleted because the default definition would be ill-formed:
 class MIAMCORE_LIBRARY TrackDAO : public GenericDAO
                        ^
model/trackdao.h:12:24: error: use of deleted function «GenericDAO& GenericDAO::operator=(const GenericDAO&)»```

**Comment by MBach** [comment] 2015-03-02 20:16
Reproduced on Arch Linux with GCC 4.9.2. However, it's working fine in Release Mode and cannot compile in Debug Mode. With MSVC 2013, both working fine!

Actually, I do not really understand why one mode is working and the other not.

**Comment by MBach** [comment] 2015-03-03 00:28
Fixed with https://github.com/MBach/Miam-Player/commit/e8d6d9f2f8efe6fbf06e7075ef94f3b021f93adf, https://github.com/MBach/Miam-Player/commit/614e3952079e99399b94bc7398083d92b77e9de3

It seems that Debug mode requires to explicit assignment operator=() because DAO are used with Q_DECLARE_METATYPE. 

In the doc [here](http://doc.qt.io/qt-5/qmetatype.html), T must be fully defined so I made the assumption that something was missing: the `use of deleted function` message was strange.

**Closed** 2015-03-03 05:53 UTC
Labels: bug
